import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { BarChart3, Clock, Shield, Trash2, ChevronRight, Download, X } from "lucide-react";
import { RiskBadge, ScoreRing, ManipulationBar } from "@/components/AnalysisResult";
import { useLanguage } from "@/i18n/LanguageContext";
import { Json } from "@/integrations/supabase/types";

interface Report {
  id: string;
  scan_type: string;
  input_summary: string;
  scam_score: number;
  risk_level: string;
  created_at: string;
  analysis: Json;
}

export default function RiskReports() {
  const { user } = useAuth();
  const { t } = useLanguage();
  const { toast } = useToast();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);

  const fetchReports = () => {
    if (!user) return;
    supabase.from("scan_reports").select("*").eq("user_id", user.id).order("created_at", { ascending: false }).limit(50)
      .then(({ data }) => { setReports((data as Report[]) || []); setLoading(false); });
  };

  useEffect(() => { fetchReports(); }, [user]);

  const handleDelete = async (id: string) => {
    const { error } = await supabase.from("scan_reports").delete().eq("id", id);
    if (error) {
      toast({ title: t("error"), description: t("deleteError"), variant: "destructive" });
    } else {
      setReports(prev => prev.filter(r => r.id !== id));
      toast({ title: t("reportDeleted") });
    }
    setDeleteId(null);
  };

  const handleDownload = (report: Report) => {
    const analysis = report.analysis as any;
    const lines = [
      `SENTRIX RISK REPORT`,
      `${"=".repeat(50)}`,
      `Date: ${new Date(report.created_at).toLocaleString()}`,
      `Scan Type: ${report.scan_type.replace("_", " ")}`,
      `Risk Level: ${report.risk_level}`,
      `Scam Score: ${report.scam_score}%`,
      ``,
      `INPUT SUMMARY`,
      `${"-".repeat(30)}`,
      report.input_summary || "N/A",
      ``,
    ];

    if (analysis) {
      lines.push(`DETAILED ANALYSIS`, `${"-".repeat(30)}`);
      if (analysis.summary) lines.push(`Summary: ${analysis.summary}`, ``);
      if (analysis.detailedExplanation) lines.push(`Explanation: ${analysis.detailedExplanation}`, ``);
      if (analysis.scamType) lines.push(`Scam Type: ${analysis.scamType}`, ``);

      if (analysis.manipulationIndicators) {
        lines.push(`MANIPULATION INDICATORS`, `${"-".repeat(30)}`);
        lines.push(`Urgency: ${analysis.manipulationIndicators.urgencyLevel}%`);
        lines.push(`Fear: ${analysis.manipulationIndicators.fearLevel}%`);
        lines.push(`Greed Trigger: ${analysis.manipulationIndicators.greedTrigger}%`);
        lines.push(`Authority Impersonation: ${analysis.manipulationIndicators.authorityImpersonation}%`);
        lines.push(``);
      }

      if (analysis.suspiciousPhrases?.length) {
        lines.push(`SUSPICIOUS PHRASES`, `${"-".repeat(30)}`);
        analysis.suspiciousPhrases.forEach((p: string) => lines.push(`• "${p}"`));
        lines.push(``);
      }

      if (analysis.reasons?.length) {
        lines.push(`KEY FINDINGS`, `${"-".repeat(30)}`);
        analysis.reasons.forEach((r: string) => lines.push(`• ${r}`));
        lines.push(``);
      }

      if (analysis.recommendations?.length) {
        lines.push(`RECOMMENDATIONS`, `${"-".repeat(30)}`);
        analysis.recommendations.forEach((r: string) => lines.push(`→ ${r}`));
        lines.push(``);
      }
    }

    lines.push(``, `${"=".repeat(50)}`, `Generated by Sentrix — AI Scam Detection Platform`);

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sentrix-report-${report.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const analysis = selectedReport?.analysis as any;

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <BarChart3 className="h-6 w-6 text-primary" /> {t("riskReportsTitle")}
        </h1>
        <p className="text-sm text-muted-foreground">{t("riskReportsDesc")}</p>
      </div>

      {loading ? (
        <p className="text-sm text-muted-foreground">{t("loadingReports")}</p>
      ) : reports.length === 0 ? (
        <div className="bg-card rounded-lg border p-8 text-center">
          <Shield className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
          <p className="font-medium">{t("noReportsYet")}</p>
          <p className="text-sm text-muted-foreground">{t("noReportsDesc")}</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map(r => (
            <div key={r.id}
              onClick={() => setSelectedReport(r)}
              className="bg-card rounded-lg border p-4 flex items-center gap-4 cursor-pointer hover:border-primary/40 transition-colors">
              <div className="text-2xl font-bold w-16 text-center" style={{
                color: r.scam_score < 30 ? "hsl(var(--success))" : r.scam_score < 70 ? "hsl(var(--warning))" : "hsl(var(--destructive))"
              }}>
                {r.scam_score}%
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-medium capitalize">{r.scan_type.replace("_", " ")}</span>
                  <RiskBadge level={r.risk_level} />
                </div>
                <p className="text-xs text-muted-foreground truncate">{r.input_summary}</p>
              </div>
              <div className="text-xs text-muted-foreground flex items-center gap-1 shrink-0">
                <Clock className="h-3 w-3" />
                {new Date(r.created_at).toLocaleDateString()}
              </div>
              <button onClick={(e) => { e.stopPropagation(); setDeleteId(r.id); }}
                className="p-2 rounded-md text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors shrink-0">
                <Trash2 className="h-4 w-4" />
              </button>
              <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" />
            </div>
          ))}
        </div>
      )}

      {/* Report detail slide-over panel */}
      {selectedReport && (
        <>
          <div className="fixed inset-0 z-50 bg-background/60 backdrop-blur-sm" onClick={() => setSelectedReport(null)} />
          <div className="fixed right-0 top-0 z-50 h-full w-full max-w-xl border-l bg-card shadow-2xl overflow-y-auto animate-in slide-in-from-right duration-300">
            <div className="sticky top-0 bg-card border-b p-4 flex items-center justify-between z-10">
              <h2 className="font-semibold">{t("reportDetails")}</h2>
              <div className="flex items-center gap-2">
                <button onClick={() => handleDownload(selectedReport)}
                  className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-3 py-1.5 rounded-md text-sm font-medium hover:opacity-90 transition-opacity">
                  <Download className="h-4 w-4" /> {t("downloadReport")}
                </button>
                <button onClick={() => setSelectedReport(null)} className="p-1.5 rounded-md hover:bg-muted transition-colors">
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>

            <div className="p-5 space-y-5">
              <div className="flex items-center gap-4 flex-wrap">
                <ScoreRing score={selectedReport.scam_score} size={100} />
                <div className="space-y-1">
                  <RiskBadge level={selectedReport.risk_level} />
                  <p className="text-sm text-muted-foreground capitalize">{selectedReport.scan_type.replace("_", " ")}</p>
                  <p className="text-xs text-muted-foreground">{new Date(selectedReport.created_at).toLocaleString()}</p>
                </div>
              </div>

              <div className="bg-muted rounded-md p-3">
                <p className="text-xs font-medium mb-1 text-muted-foreground">Input</p>
                <p className="text-sm">{selectedReport.input_summary}</p>
              </div>

              {analysis && (
                <>
                  {analysis.summary && (
                    <div>
                      <h4 className="font-semibold text-sm mb-1">{t("summary") || "Summary"}</h4>
                      <p className="text-sm text-muted-foreground">{analysis.summary}</p>
                    </div>
                  )}

                  {analysis.scamType && analysis.scamType !== "None detected" && (
                    <p className="text-xs font-mono bg-muted px-2 py-1 rounded inline-block">Type: {analysis.scamType}</p>
                  )}

                  {analysis.manipulationIndicators && (
                    <div className="bg-card rounded-lg border p-4 space-y-3">
                      <h4 className="font-semibold text-sm">{t("psychManipulation")}</h4>
                      <ManipulationBar label={t("urgency")} value={analysis.manipulationIndicators.urgencyLevel || 0} />
                      <ManipulationBar label={t("fear")} value={analysis.manipulationIndicators.fearLevel || 0} />
                      <ManipulationBar label={t("greedTrigger")} value={analysis.manipulationIndicators.greedTrigger || 0} />
                      <ManipulationBar label={t("authorityImpersonation")} value={analysis.manipulationIndicators.authorityImpersonation || 0} />
                    </div>
                  )}

                  {analysis.suspiciousPhrases?.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-sm mb-2">{t("suspiciousPhrases")}</h4>
                      <div className="flex flex-wrap gap-2">
                        {analysis.suspiciousPhrases.map((p: string, i: number) => (
                          <span key={i} className="bg-destructive/10 text-destructive text-xs px-2 py-1 rounded font-mono">"{p}"</span>
                        ))}
                      </div>
                    </div>
                  )}

                  {analysis.reasons?.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-sm mb-2">{t("keyFindings")}</h4>
                      <ul className="space-y-1 text-sm text-muted-foreground">
                        {analysis.reasons.map((r: string, i: number) => <li key={i} className="flex gap-2"><span className="text-warning">•</span>{r}</li>)}
                      </ul>
                    </div>
                  )}

                  {analysis.detailedExplanation && (
                    <div>
                      <h4 className="font-semibold text-sm mb-2">{t("detailedAnalysis")}</h4>
                      <p className="text-sm text-muted-foreground leading-relaxed">{analysis.detailedExplanation}</p>
                    </div>
                  )}

                  {analysis.recommendations?.length > 0 && (
                    <div className="bg-primary/5 rounded-lg border border-primary/20 p-4">
                      <h4 className="font-semibold text-sm mb-2 text-primary">{t("recommendations")}</h4>
                      <ul className="space-y-1 text-sm text-muted-foreground">
                        {analysis.recommendations.map((r: string, i: number) => <li key={i} className="flex gap-2"><span className="text-primary">→</span>{r}</li>)}
                      </ul>
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        </>
      )}

      {/* Delete confirmation dialog - anchored near the delete button */}
      {deleteId && (
        <div className="fixed inset-0 z-50 bg-background/60 backdrop-blur-sm" onClick={() => setDeleteId(null)}>
          <div className="fixed top-1/3 right-8 z-50 bg-card border rounded-lg p-6 max-w-sm w-full shadow-xl space-y-4 animate-in fade-in zoom-in-95 duration-200" onClick={e => e.stopPropagation()}>
            <p className="font-medium text-sm">{t("confirmDelete")}</p>
            <div className="flex gap-3 justify-end">
              <button onClick={() => setDeleteId(null)}
                className="px-4 py-2 rounded-md text-sm bg-muted hover:bg-muted/80 transition-colors">
                {t("cancel")}
              </button>
              <button onClick={() => handleDelete(deleteId)}
                className="px-4 py-2 rounded-md text-sm bg-destructive text-destructive-foreground hover:opacity-90 transition-opacity">
                {t("confirm")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
